on:
  push:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Build
        run: crystal build src/parser.cr
  specs:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run tests
        run: crystal spec
  format:
    runs-on: ubuntu
    needs: [specs]
    steps:
      - name: Check formatting
        run: crystal tool format --check
